Create homepage layout
FrancoisLunick/AmazonClone pull request #8
Opened 2024-06-29 19:06 UTC by FrancoisLunick

This pull request implements the initial layout for the homepage of the Amazon Clone project. It includes the following components and styles:

### Components

- **NavigationBar**: The navigation bar at the top of the page with links to the homepage, login, signup, and cart.
- **FeaturedProducts**: A section displaying featured products.
- **Categories**: A section displaying product categories.

### Styles

- **NavigationBar.css**: Styles for the navigation bar, including layout, spacing, and color settings.
- **FeaturedProducts.css**: Styles for the featured products section, including grid layout and individual product styling.
- **Categories.css**: Styles for the categories section, including grid layout and individual category styling.
- **Homepage.css**: General styles for the homepage layout, including responsive styles for different screen sizes.

### Changes

- `src/components/NavigationBar.js`: Added NavigationBar component with links and styles.
- `src/components/FeaturedProducts.js`: Added FeaturedProducts component with placeholder products.
- `src/components/Categories.js`: Added Categories component with placeholder categories.
- `src/styles/NavigationBar.css`: Added styles for NavigationBar component.
- `src/styles/FeaturedProducts.css`: Added styles for FeaturedProducts component.
- `src/styles/Categories.css`: Added styles for Categories component.
- `src/styles/Homepage.css`: Added styles for Homepage component, including responsive design.
- `src/Homepage.js`: Updated Homepage component to include NavigationBar, FeaturedProducts, and Categories components.

### Acceptance Criteria

- Homepage layout is designed and implemented.
- Sections for featured products, categories, etc., are added.
- Layout is responsive and looks good on different devices.

### Testing

- Verified that the homepage displays correctly with all sections included.
- Ensured that the layout is responsive and adapts to different screen sizes.

2024-06-30 22:28 UTC, Cybersunami commented on amazon_clone/src/Homepage.js
> +    <div className='homepage'>Homepage
"Homepage" should not be visible.

2024-06-30 22:31 UTC, Cybersunami commented
In App.js the root path is still the signup page.

2024-06-30 22:39 UTC, Cybersunami requested changes
The Homepage text is visible and the root path is set to the signup page.
![Screenshot 2024-06-30 at 6 35 18 PM (2)](https://github.com/FrancoisLunick/AmazonClone/assets/172165637/dbf35da8-dda6-4a0d-93c6-1c22b5a96bfd)

2024-06-30 23:24 UTC, FrancoisLunick commented on amazon_clone/src/Homepage.js
> +    <div className='homepage'>Homepage
I removed the text

2024-07-01 15:14 UTC, Cybersunami approved these changes

2024-07-01 15:15 UTC, merged